---
services:
  cockroachdb:
    image: cockroachdb/cockroach:v25.4.6
    command: start-single-node --insecure
    ports:
    - 26257:26257
    - 8080:8080
    volumes:
    - cockroach_data:/cockroach/cockroach-data
    restart: on-failure
volumes:
  cockroach_data:
...
